### ISSUE TITLE
Module is broken on v3

### ISSUE THREAD

**Issue by onfire4g05** [bitfocus/companion-module-roland-v60hd#13] opened 2023-10-29 15:01 UTC
Will not connect and constantly crashes on v3. Logs aren't very helpful (`error: /Applications/Companion.app/Contents/Resources/bundled-modules/roland-v60hd/main.js:2`).

**Comment by jsnyder886** [comment] 2023-11-03 22:40
I second this.  I have tried it on stable release 3.1.1 and on the latest beta, 6460.

**Comment by jsnyder886** [comment] 2023-11-26 18:02
@josephdadams or @jrviz any chance you would have a few minutes to spare to check this out?  This is my last module I need to be able to use v3 of companion.  Thank you sir!

**Comment by josephdadams** [comment] 2023-11-26 20:35
I will see what I can do

**Comment by jetsetstudio** [comment] 2024-01-10 16:17
@josephdadams greetings and thanks for all you do with Bitfocus Companion! I have seen your name around over the past few years since I have been a companion end user. 
Just recently I have found that the module V-60HD v2.0.0 for Companion V3.1.1 has been losing connection seemingly in sync with the polling interval causing erratic/lack of control and no button feedback. I would very much appreciate your expertise if possible.  Not having such programming and scripting skills myself, for me you are certainly doing the Lords work. Cheers and thanks again.
Curtis

**Comment by josephdadams** [comment] 2024-01-11 15:26
I don’t have one of these devices so I can’t help debug or fix. I recommend going back to a version of companion where it did work if you need it.

**Comment by onfire4g05** [comment] 2024-01-11 15:35
Maybe it'd be better to downgrade the module to the pre-v3 one, since it worked?

**Comment by jetsetstudio** [comment] 2024-01-11 17:05
@josephdadams  I actually have access to that video switcher and am willing to attempt to debug and test. If I were to attempt this, what process or tools would you suggest I use? Run companion networked with the switcher and wireshark software? or use companion logs? I will gladly go down this rabbit hole for this module. Any tips to get me started would be greatly appretiated. I do work have a coworker that has scripting experience and may seek his help. Just trying to gather as much info to give him as I can as well as dabble into it myself. Thanks again though @josephdadams.

**Comment by andrewc2** [comment] 2024-01-14 16:53
I have access to one as well, actually came to provide more logs:

[error.txt](https://github.com/bitfocus/companion-module-roland-v60hd/files/13932291/error.txt)

**Comment by josephdadams** [comment] 2024-01-14 17:01
Thanks. That helped slightly. I pushed some fixes. v2.0.1 of the module. See if it helps.

**Comment by andrewc2** [comment] 2024-01-14 17:29
I would love to help but I'm not so sure how to make this a working module to test it, following the instructions from bitfocus results in this error:

```js
error: node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@companion-module/base'
Require stack:
- D:\companion-module-dev\roland-v60hd\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\companion-module-dev\roland-v60hd\index.js:3:57)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\companion-module-dev\\roland-v60hd\\index.js' ]
}

Node.js v18.18.1
```

**Comment by andrewc2** [comment] 2024-01-14 17:47
Okay I realized that bitfocus automatically builds a module which I need to download from the companion-bundled-modules repo instead of this repo. 

Seems as though nothing has changed? I've deleted the v2.0.0 module completely from the /bundled-modules/ folder and confirmed it is loading v2.0.1 from the development folder.

[error 2.txt](https://github.com/bitfocus/companion-module-roland-v60hd/files/13932523/error.2.txt)

**Comment by josephdadams** [comment] 2024-01-14 19:10
I wouldn’t say nothing changed. This error is different. I will push a fix later

**Comment by josephdadams** [comment] 2024-01-15 19:12
Try v2.0.2 when you have time.

**Comment by jetsetstudio** [comment] 2024-01-15 19:38
Will do. Thanks again!

**Comment by andrewc2** [comment] 2024-01-16 13:56
I'll have access to the equipment again on Friday and will report back.

**Comment by josephdadams** [comment] 2024-01-20 03:44
Awaiting your report

**Comment by jetsetstudio** [comment] 2024-01-20 04:25
I will be able to test all next week on one of those switchers.  Only thing
is, I am having trouble figuring out how to actually add the new module
version into companion.

**Comment by josephdadams** [comment] 2024-01-20 04:44
You just download a new beta version

**Comment by jetsetstudio** [comment] 2024-01-20 10:12
Wow. That is so much easier than what I was trying to do. I was trying to
figure out how to "fork a branch" or "clone a repository" and paste your
code into it...I was having a time. Lol. I was trying to somehow add custom
local code into a stable companion and I certainly didn't know what I was
doing.

**Comment by andrewc2** [comment] 2024-01-21 13:36
Here is the latest error:

[ERR.txt](https://github.com/bitfocus/companion-module-roland-v60hd/files/14001466/ERR.txt)

**Comment by josephdadams** [comment] 2024-01-21 13:59
I pushed a fix for this just now

**Comment by andrewc2** [comment] 2024-01-21 14:30
[ERR - Copy.txt](https://github.com/bitfocus/companion-module-roland-v60hd/files/14001646/ERR.-.Copy.txt)

**Comment by josephdadams** [comment] 2024-01-22 13:00
This is fun. Are you having fun yet? try v2.0.4 when you have a moment.

**Comment by andrewc2** [comment] 2024-01-22 14:28
I appreciate your willingness to chase these bugs. I won't have access until the weekend to test and will report back then if @jetsetstudio isn't able to.

**Comment by jetsetstudio** [comment] 2024-01-22 14:43
I will dona test today.

**Comment by onfire4g05** [comment] 2024-01-22 14:44
- When adding module for the first time, it continually tries to connect to the default IP. Had to completely restart Companion to fix it.
- After restart, it tried the correct IP but continually times out and I can no longer edit the configuration.

I can't test beyond that. I did download beta 6658, which doesn't appear to have 2.0.4, but rather 2.0.3.

@josephdadams I can give you access to a computer that has a V60, if that'd help diagnose the issues. Slack me if interested.

```
24.01.22 08:39:00 Instance/ModuleHost: Starting connection: "v-60hd"(t1jyIBiRnjyg9g1u2Bk-Z)
24.01.22 08:39:00 UI/Server: new url: http://10.152.61.9:8888/
24.01.22 08:39:00 Instance/ModuleHost: Connection "v-60hd" started
24.01.22 08:39:00 UI/Handler: socket Lcri4bSvLXZgtYgvAAAB connected
24.01.22 08:39:00 Instance/ModuleHost: Registered module client "t1jyIBiRnjyg9g1u2Bk-Z"
24.01.22 08:39:00 Instance/Controller: instance "v-60hd" configuration updated
24.01.22 08:39:01 UI/Update: fresh update data received Remember, this is a beta version!
24.01.22 08:39:01 UI/Handler: socket JtXrlEhZDtJ9OZwOAAAD connected
24.01.22 08:39:01 UI/Handler: socket JtXrlEhZDtJ9OZwOAAAD disconnected
24.01.22 08:39:01 UI/Handler: socket bKo_iFU0wQNINYK5AAAF connected
24.01.22 08:39:02 Instance/Wrapper/v-60hd: Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",\"internal:time_hms_12\"]}"}
24.01.22 08:39:08 Instance/Wrapper/v-60hd: Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",\"internal:time_hms_12\"]}"}
24.01.22 08:39:10 Instance/Wrapper/v-60hd: Error getting config fields: Call timed out
24.01.22 08:39:12 Instance/Wrapper/v-60hd: Error getting config fields: Call timed out
24.01.22 08:39:14 Instance/Wrapper/v-60hd: Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",\"internal:time_hms_12\"]}"}
24.01.22 08:39:14 Instance/Wrapper/v-60hd: Error getting config fields: Call timed out
24.01.22 08:39:16 Instance/Wrapper/v-60hd: Error getting config fields: Call timed out
24.01.22 08:39:18 Instance/Wrapper/v-60hd: Error getting config fields: Call timed out
```

**Comment by josephdadams** [comment] 2024-01-22 14:48
I fixed the default IP issue in v2.0.5.

I'm not really interested in spending a bunch more time on it. I don't own and have never used any of these Roland devices... I just wrote the modules to be nice many years ago.

**Comment by jetsetstudio** [comment] 2024-01-22 15:27
Hey Joseph,
What version of companion be it beta or experimental and version should
have your 2.0.5 for the Roland V-60?

Thanks again for all this. If at any point your ready to call it quits if
I'm bugging you just say the word. I'm gonna test it there once I get the
right companion version

**Comment by josephdadams** [comment] 2024-01-22 15:28
beta

**Comment by jetsetstudio** [comment] 2024-01-22 15:55
I'm only seeing version 2.0.3 in beta version 6658.

**Comment by andrewc2** [comment] 2024-01-22 16:29
I just download the files from here to bypass that beta process: https://github.com/bitfocus/companion-bundled-modules/tree/main/roland-v60hd into a dev module, and deleted the original module. One could also just drop these files in the main /roland-v60hd/ folder.

**Comment by josephdadams** [comment] 2024-01-22 16:40
Builds only run like every 6 hours, not on pushes

**Comment by jetsetstudio** [comment] 2024-01-22 16:42
oh gotcha

**Comment by jetsetstudio** [comment] 2024-01-22 17:37
It seems the connection is made and feedback works but control commands do
not send to the device. I have attached a log.
thanks
Curtis

**Comment by jetsetstudio** [comment] 2024-01-23 14:18
Actually just some update testing info,
- Module Instance connection seems stable
-Button feedback seems good.
- Most commands seem to work, (haven't test them all yet)
Except The "V-60:Select PVW Channel" commands don't seem to work. Yet
feedback for what is in PVW does work.

**Comment by josephdadams** [comment] 2024-01-23 23:56
If it works to select in PGM or AUX, check to make sure your source input number is correct. The code to do these functions is nearly identical.

**Comment by jetsetstudio** [comment] 2024-01-24 00:00
I'm confident I did check that but I will be sure to check again tomorrow.
That could be possible. I also noticed that sometimes the instance sort of
goes "to sleep" and button feedback stops. A quick module instance refresh
and its back in business.


Thanks again!

**Comment by josephdadams** [comment] 2024-01-24 00:02
🤔 I’ll look into that one. But glad disable/enable works for now!

**Comment by jetsetstudio** [comment] 2024-01-24 14:51
Not sure if this has anything to do with it...but feedback for the preview
channel is named v-60hd: Preset Status for Input.

The select action refers to Preset Channel as PVW  channel. I wonder if the
action to select PVW should be select Preset Channel.

**Comment by josephdadams** [comment] 2024-01-24 17:48
I'm ok with either. I made the action list, I believe another developer added the feedbacks. I prefer "preview" over "preset" but I don't mind calling it something consistent

**Comment by jetsetstudio** [comment] 2024-01-24 17:53
I also like "preview" so it doesn't confuse with memory presets.

**Comment by mntechnogeek** [comment] 2024-01-24 20:02
Hi. Trying to use this module using v3.3.0 (3.3.0+6688-main-d122fab2) Beta on a V-60HD with the latest version of the firmware (v3.10 and it's companion NPU 1039).

The connection seems solid, but button clicks don't actually trigger anything.  
Checked the log, and the first entry was...

"Instance/Modules: Error loading module from "C:\Program Files\Companion\resources\bundled-modules\rstream-api": Error: manifest incorrectly references template module 'companion-module-your-module-name'

Pressing one of my buttons designed to bring a source up on the Preview bus, I get another error...

"Instance/Wrapper/v-60hd: ERR (Syntax Error)  - Command = "

I just rebuilt the button from scratch and the error I got from trying to preview source 5 was...

"Instance/Wrapper/v-60hd: ERR (Syntax Error)  - Command = PVW:4 ;"

I'm surmised the arguments are zero-based, not referencing what we meatsacks do by calling the first entry "1"

Does any of this help in getting the module usable?

**Comment by josephdadams** [comment] 2024-01-25 12:50
> "Instance/Modules: Error loading module from "C:\Program Files\Companion\resources\bundled-modules\rstream-api": Error: manifest incorrectly references template module 'companion-module-your-module-name'

This error is not related to this module - it is a problem with the restream module.

> "Instance/Wrapper/v-60hd: ERR (Syntax Error) - Command = PVW:4 ;"

I found an error in the code here - at some point during my conversion to the v3 API I changed the command from `PST` to `PVW`, and it's obviously supposed to be `PST`.

I've corrected this in module version v2.0.6.

**Comment by mntechnogeek** [comment] 2024-01-25 14:31
Thank you! I'll check it out.

Also: the Restream module error seems spurious. I never engaged that module, and I just saw someone else reported the same error on Companion launch. Not pointing fingers, but I'm curious if it's an issue in core Companion code...?

(Not a programmer ;-)

**Comment by jetsetstudio** [comment] 2024-01-25 14:47
Is this 2.0.6 update for the same 3.2.0 +6658 beta? Or for a different
version?

**Comment by josephdadams** [comment] 2024-01-25 15:29
Builds run every 6 hours so there should be a new beta 3.2.0 +xxxx sometime today that has v2.0.6 of this module in it.

**Comment by jetsetstudio** [comment] 2024-01-25 15:32
Okay awesome. I will keep an eye out. Thanks.

**Comment by jetsetstudio** [comment] 2024-01-25 19:33
Joseph Adams you are a wizzard!
So far so good. The new beta with your v2.0.6 of roland v-60hd feels solid.
All the core functionality and feedback is bang on. I'm continuing to test
and monitor but I believe you have done it! Much appreciated!

Curtis

**Comment by josephdadams** [comment] 2024-01-26 11:46
Great.

**Closed as completed by josephdadams** 2024-01-26 11:46 UTC

**Comment by andrewc2** [comment] 2024-01-28 13:41
It's working for me but I do see these in the logs:

```
24.01.28 08:21:50 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:21:53 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:21:57 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = PGM:6;
24.01.28 08:22:00 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = undefined
24.01.28 08:22:02 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:22:05 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = undefined
24.01.28 08:22:06 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = undefined
24.01.28 08:22:09 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = CUT;
24.01.28 08:22:12 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:22:14 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:40:12 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = PST:4;
24.01.28 08:40:13 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = undefined
24.01.28 08:40:25 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:40:31 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:40:33 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
24.01.28 08:40:35 Instance/Wrapper/v-60hd: ERR: (Syntax Error) - Command = QPL:7
```

**Comment by josephdadams** [comment] 2024-01-28 13:54
I am going to push a fix for the QPL - I think it is because the STX is not being sent beforehand. Not sure about the `undefined`.

**Comment by andrewc2** [comment] 2024-01-28 17:54
Before I think it was just when buttons were pressed but now on v.2.0.7 it's like a heart beat 

```
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = undefined
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = QPL:7;
error: ERR: (Syntax Error) - Command = undefined
```

**Comment by josephdadams** [comment] 2024-01-29 16:38
@andrewc2 what firmware version is your roland on?

**Comment by andrewc2** [comment] 2024-01-29 16:54
I will confirm this weekend but since their firmware page is showing a publish date of 4/2022, I'm almost positive it's on the latest: MAIN : 3.10 b000 | NPU : 1.039.

**Comment by jsnyder886** [comment] 2024-01-29 18:37
@josephdadams Thanks so much for all of your efforts on this!  I'm having the same heartbeat error described by @andrewc2 on my system.  I just ran the VER command over telnet (I'm nowhere near my console to physically look at it for the time being).  It's reporting version 3.10.  

Hope this helps, and thanks again so much!

**Comment by josephdadams** [comment] 2024-01-30 12:42
For now you can just set the polling interval to 0 and it should stop sending the QPL command.
